### PR TITLE
Add full markup support

### LINKED ISSUE #231: ' doesn't show up properly
' shows as &39; instead

### PR DESCRIPTION
**Pull request by michaelocurtis2**
Should fix #231,needs testing first

### CODE REVIEW

**Comment by tintou** [comment]
We should probably use the same solution as in https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/messageList.js#L17

**Comment by tintou** [comment]
Thanks for looking at it!

**Comment by 1902276** [comment]
> Thanks for looking at it!

I've had another stab, using the GNOME-shell

**Comment by 1902276** [comment]
Whatever fix is used, will need to be duplicated at https://github.com/elementary/notifications/blob/master/src/Notification.vala

**Comment by jeremypw** [comment]
@Michael-Curtis0 Could you create a matching PR for `elementary/notifications` and check that they work together as expected?  Thanks.  Marking this as `draft` for now as it cannot work alone.  Please revert to `review required` when ready.

**Pull request closed without merging**
