### PR TITLE
Modified plural form

### PR DESCRIPTION
**Pull request by yarons**
This should support the dual form in time terms in Hebrew, should only apply to this file, all the others seem fine for now.

### CODE REVIEW

**Comment by danrabbit** [comment]
Hey @yarons thanks for your pull request! However, translations for this repo are managed and reviewed [here in Weblate](https://l10n.elementary.io/projects/wingpanel/wingpanel-indicator-notifications/)

**Comment by yarons** [comment]
There's no way to change plural forms individually in Weblate. 

I need the changes from Weblate merged back and then change the plural forms formula.

**Comment by leonardo-lemos** [comment]
I modified the number of plurals and plural form in elementary's Weblate.

**Comment by yarons** [comment]
You changed it only for this file?

**Pull request closed without merging**
