### PR TITLE
Notification: Add is_transient property

### PR DESCRIPTION
**Pull request by danrabbit**
Instead of `get_is_valid` function. This allows us to make hints private to the dbus message constructor and makes it more clear what we mean by "valid"

### CODE REVIEW

**Comment by jeremypw** [comment]
Seems to lose a test `app_info != null`.  Now only testing for transience. Not sure if this matters?

**Comment by danrabbit** [comment]
@jeremypw Yeah I have no idea why this was testing for appinfo in the first place, since having appinfo or not doesn't change whether the notification hints say that it's transient. But in any case, it doesn't seem like it's possible to have null appinfo since we set it in both constructors

**Comment by jeremypw** [comment]
Actually, looking at the code `app_info` is a nullable member of Notification.  There is a fallback in the `.from_message` constructor but not in the `.from_data` constructor.  I would suggest `app_info` be made a non-nullable property which is constructed as the fallback then only replaced with another DesktopAppInfo after testing that it is non-null.  The corresponding member in AppEntry should then be made a non-nullable construct property.  Also there are null checks in NotificationEntry and NotificationsList  which are redundant if `notification.app_info` cannot be null and should be removed.

**Comment by danrabbit** [comment]
@jeremypw yeah the app info stuff definitely needs some work in another branch. I'm not really sure why we create a fallback app info. It probably should be allowed to be null, but this needs some more investigation

Regardless I don't see a reason why we wouldn't respect notification transience depending on the presence of appinfo

**Comment by jeremypw** [comment]
It just that this code will crash at:
```
        if (!((DesktopAppInfo)notification.app_info).get_boolean ("X-GNOME-UsesNotifications")) {
            app_id = "gala-other";
        }
```
 if it receives a notification that is not transient and also has no app_info.  I am not sure how likely that is in normal practice but presumably such a notification could theoretically be crafted.  So it would be best to insert a null check here.

**Review by jeremypw — APPROVED** [review]
Null app_info now fixed in master - no regressions found.

**Pull request merged**
