### PR TITLE
AppEntry: Make remove notification private

### PR DESCRIPTION
**Pull request by danrabbit**

### CODE REVIEW

**Review by jeremypw — CHANGES_REQUESTED** [review]
This seems to stop the "Clear all notifications" button working properly.   The notifications list needs a way of removing the app_entries.  Actually I am getting this issue with master as well :open_mouth:  - investigating.

**Comment by jeremypw** [comment]
The culprit is this commit - 770888a3fe8b7b610622a7f73ff67257a760daa7.  `clear_all ()` just clears the hashmap and no longer results in the notification entries being removed.

**Comment by jeremypw** [comment]
After merging the clear all fix this PR causes a regression so that Clear All no longer works properly. Although the notification indicator shows the "No Notifications" icon, the popover still contains a list of notifications which never got destroyed.

**Comment by danrabbit** [comment]
Yeah, this makes more sense now I think since that code was fixed. Woops

**Pull request closed without merging**
