### PR TITLE
Add  character codes to regex so that they get parsed properly

### LINKED ISSUE #58: The character ' is not rendered correctly
This character (') is not rendered correctly when sent by discord
(However it does work with notify-send)
 

It's rendered as `&#39;`

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/67492591-the-character-is-not-rendered-correctly?utm_campaign=plugin&utm_content=tracker%2F60476261&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F60476261&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by EbonJaeger**
Notifications from some apps (such as Discord and Tootle) have character codes (`&#39;` and `&nbsp;`) in the ending message body. This PR ensures that they are properly replaced with the correct characters.

This only fixes the indicator applet's list; the notification popups still show the character codes. Those are fixed by https://github.com/elementary/gala/pull/437.

Tested by getting someone on Discord to send me a message with an ' in it to verify that it is displayed properly.

Fixes #58

### CODE REVIEW

**Comment by EbonJaeger** [comment]
Uh. No idea why Travis is falling over. It builds and runs find on my machine.

**Review by peteruithoven — DISMISSED** [review]
Nice!

**Comment by jeremypw** [comment]
@EbonJaeger Converting to draft as there a change request and no recent activity.  Is this something you are still available to work on?

**Comment by lenemter** [comment]
I'll close this since the fix is already merged.

**Pull request closed without merging**
